[package]
name = "app"
version = "0.1.0"
edition = "2021"
authors = ["Igor Ilic"]
repository = "https://github.com/igorilic/rust-npm-package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
